# -*- coding: utf-8 -*-
#:import hex kivy.utils.get_color_from_hex
#:import markup kivy.core.text

<Test04Screen>:
    id: test_04
    name: "test_04"
    a: a
    b: b
    c: c

    BoxLayout:
        orientation: "vertical"

        MDToolbar:
            id: toolbar
            title: "Test 1"
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["arrow-left", lambda x: app.change_screen('test_screen', 'right')]]
            right_action_items: [["home", lambda x: app.change_screen('main', 'right')]]
            elevation: 10

        MDGridLayout:
            cols: 1
            padding: 1,1

            ScrollView:

                MDList:
                    padding: 1,1

                    MDLabel:
                        padding: 5,5
                        text: '1. Ktory z trzech glownych parametrow obrobki ma najwiekszy wplyw na [b]trwalosc ostrza[/b] ?'
                        markup: True
                        font_style: "Caption"
                        text_size: self.width, None
                        size_hint: 1, None
                        theme_text_color: "Primary"
                        text_color: app.theme_cls.primary_color

                        user_font_size: "30sp"
                        height: self.texture_size[1]
                        canvas.before:
                            Color:
                                rgba: hex('#d2ebf7')
                            Rectangle:
                                pos: self.pos
                                size: self.size

                    MDSeparator:
                        height:

                    ListItemWithCheckbox:
                        text: 'Glebokosc skrawania'

                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-a-circle-outline"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'Posuw'
                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-b-circle-outline"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'Predkosc skrawania'
                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-c-circle-outline"

                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)

                    MDSeparator:
                        height:
                    MDLabel:
                        padding: 5,5
                        text: '2. Jakie jest oznaczenie wg ISO pokrywanych [b]plytek weglikowych[/b]?'
                        markup: True
                        font_style: "Caption"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]

                        canvas.before:
                            Color:
                                rgba: hex('#d2ebf7')
                            Rectangle:
                                pos: self.pos
                                size: self.size
                    MDSeparator:
                        height:

                    ListItemWithCheckbox:
                        text: 'HC'
                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-a-circle-outline"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'CC'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-b-circle-outline"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'PD'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-c-circle-outline"


                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)


                    MDSeparator:
                        height:

                    MDLabel:
                        padding: 5,5
                        text: '3. Jakie sa dwie glowne metody pokrywania [b]plytek weglikowych[/b]?'
                        markup: True
                        font_style: "Caption"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]

                        canvas.before:
                            Color:
                                rgba: hex('#d2ebf7')
                            Rectangle:
                                pos: self.pos
                                size: self.size
                    MDSeparator:
                        height:

                    ListItemWithCheckbox:
                        text: 'AVD'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-a-circle-outline"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'CVD'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-b-circle-outline"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'CBN'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-c-circle-outline"


                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)

                    MDSeparator:
                        height:
                    MDLabel:
                        padding: 5,5
                        text: '4. Jaka jest definicja [b]wartosci oporu wlasciwego[/b] skrawania?'
                        markup: True
                        font_style: "Caption"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]

                        canvas.before:
                            Color:
                                rgba: hex('#d2ebf7')
                            Rectangle:
                                pos: self.pos
                                size: self.size

                    MDSeparator:
                        height:

                    ListItemWithCheckbox:
                        text: 'Maksymalna grubosc wiorow'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-a-circle-outline"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'Wspolczynnik korekcji'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-b-circle-outline"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'Sila posuwowa'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        height: "42dp"
                        IconLeftWidget:
                            icon: "alpha-c-circle-outline"

                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)

    MDFloatingActionButton:
        icon: "playlist-check"
        theme_text_color: "Custom"
        text_color: 1,1,1,1
        user_font_size: "20sp"
        md_bg_color: app.theme_cls.primary_color
        pos_hint: {"center_x": 0.925, "center_y": 0.08}
        elevation_normal: 9
        on_release:
            root.on_checkbox_active()









