# -*- coding: utf-8 -*-
<Test01Screen>:
    id: test_01
    name: "test_01"
    a: a
    b: b
    c: c

    BoxLayout:
        orientation: "vertical"

        MDToolbar:
            id: toolbar
            title: "Test 1"
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["arrow-left", lambda x: app.change_screen('test_screen', 'right')]]
            right_action_items: [['bell-check', lambda x: root.on_checkbox_active()]]

        MDGridLayout:
            cols: 1
            padding: 3, 4
            spacing: 2


            ScrollView:
                spacing: 2

                MDList:
                    spacing: 2
                    MDLabel:
                        text: '1). Ktory z trzech glownych parametrow obrobki ma najwiekszy wplyw na trwalosc ostrza ?'
                        md_bg_color: app.theme_cls.primary_color
                        font_style: "Body2"
                        text_size: self.width, None
                        size_hint: 1, None
                        halign: "center"
                        user_font_size: "30sp"
                        height: self.texture_size[1]
                        theme_text_color: "Primary"
                        theme_text_color: "Custom"

                    MDSeparator:
                        height: "2dp"
                        rgba: 0.7, 0.7, 0.7, 1
                        md_bg_color: app.theme_cls.primary_color

                    ListItemWithCheckbox:
                        text: 'Glebokosc skrawania'

                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-a-circle"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)



                    ListItemWithCheckbox:
                        text: 'Posuw'
                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-b-circle"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)


                    ListItemWithCheckbox:
                        text: 'Predkosc skrawania'
                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-c-circle"

                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)



                    MDLabel:
                        text: '2). Jakie jest oznaczenie wg ISO pokrywanych plytek weglikowych?'
                        halign: "center"
                        font_style: "Body2"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]
                        halign: "center"

                    MDSeparator:
                        height: "2dp"


                    ListItemWithCheckbox:
                        text: 'HC'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-a-circle"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)


                    ListItemWithCheckbox:
                        text: 'CC'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-b-circle"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)



                    ListItemWithCheckbox:
                        text: 'PD'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-c-circle"


                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)



                    MDLabel:
                        text: '3). Jakie sa dwie glowne metody pokrywania plytek weglikowych?'

                        font_style: "Body2"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]
                        halign: "center"

                    MDSeparator:
                        height: "2dp"

                    ListItemWithCheckbox:
                        text: 'AVD'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-a-circle"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)



                    ListItemWithCheckbox:
                        text: 'CVD'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-b-circle"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)



                    ListItemWithCheckbox:
                        text: 'CBN'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-c-circle"


                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)



                    MDLabel:
                        text: '4). Jaka jest definicja wartosci oporu wlasciwego skrawania??'

                        font_style: "Body2"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]
                        halign: "center"

                    MDSeparator:
                        height: "2dp"

                    ListItemWithCheckbox:
                        text: 'Maksymalna grubosc wiorow'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-a-circle"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)



                    ListItemWithCheckbox:
                        text: 'Wspolczynnik korekcji'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-b-circle"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)



                    ListItemWithCheckbox:
                        text: 'Sila posuwowa'

                        md_bg_color: 0, 0, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-c-circle"


                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)








