# -*- coding: utf-8 -*-
<Test01Screen>:
    id: test_01
    name: "test_01"
    a: a
    b: b
    c: c

    BoxLayout:
        orientation: "vertical"
        canvas:
            Color:
                rgb: 204, 224, 255
            Rectangle:
                size: self.size



        MDToolbar:
            id: toolbar
            title: "Test 1"
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["arrow-left", lambda x: app.change_screen('test_screen', 'right')]]
            right_action_items: [['bell-check', lambda x: root.on_checkbox_active()]]


        GridLayout:
            cols: 1
            padding: 3, 3

            ScrollView:

                MDList:
                    spacing: 1
                    MDLabel:
                        text: '1. Ktory z trzech glownych parametrow obrobki ma najwiekszy wplyw na trwalosc ostrza ?'

                        font_style: "Body2"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]

                    ListItemWithCheckbox:
                        text: 'Glebokosc skrawania'
                        bg_color: 'Body 1'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-a-circle"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'Posuw'
                        bg_color: 'Custom'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-b-circle"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'Predkosc skrawania'
                        bg_color: 'Custom'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-c-circle"


                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)
                    MDLabel:
                        text: '2. Jakie jest oznaczenie wg ISO pokrywanych plytek weglikowych?'

                        font_style: "Body2"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]

                    ListItemWithCheckbox:
                        text: 'HC'
                        bg_color: 'Body 1'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-a-circle"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'CC'
                        bg_color: 'Custom'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-b-circle"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'PD'
                        bg_color: 'Custom'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-c-circle"


                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)

                    MDLabel:
                        text: '3. Jakie sa dwie glowne metody pokrywania plytek weglikowych?'

                        font_style: "Body2"
                        text_size: self.width, None
                        size_hint: 1, None
                        user_font_size: "30sp"
                        height: self.texture_size[1]

                    ListItemWithCheckbox:
                        text: 'AVD'
                        bg_color: 'Body 1'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-a-circle"

                        RightCheckbox:
                            id: a
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'CVD'
                        bg_color: 'Custom'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-b-circle"

                        RightCheckbox:
                            id: b
                            name: 'b'
                            size: dp(35), dp(35)

                    ListItemWithCheckbox:
                        text: 'CBN'
                        bg_color: 'Custom'
                        bg_color: 1, 1, 0
                        font_style: "Caption"
                        text_size: self.size
                        IconLeftWidget:
                            icon: "alpha-c-circle"


                        RightCheckbox:
                            id: c
                            size: dp(35), dp(35)





